services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
        #$projectDir: '%kernel.project_dir%'

    Markocupic\BootstrapResponsiveYoutubeEmbed\:
        resource: ../../
        exclude: ../../{DependencyInjection,Resources,Model}
