services:
    _defaults:
        autowire: true
        autoconfigure: true

    Markocupic\BootstrapResponsiveYoutubeEmbed\:
        resource: ../../
        exclude: ../../{DependencyInjection,Resources,Model}
